/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateAppSettingArgs } from "./CreateAppSettingArgs";
import { UpdateAppSettingArgs } from "./UpdateAppSettingArgs";
import { DeleteAppSettingArgs } from "./DeleteAppSettingArgs";
import { AppSettingCountArgs } from "./AppSettingCountArgs";
import { AppSettingFindManyArgs } from "./AppSettingFindManyArgs";
import { AppSettingFindUniqueArgs } from "./AppSettingFindUniqueArgs";
import { AppSetting } from "./AppSetting";
import { AppSettingService } from "../appSetting.service";
@graphql.Resolver(() => AppSetting)
export class AppSettingResolverBase {
  constructor(protected readonly service: AppSettingService) {}

  async _appSettingsMeta(
    @graphql.Args() args: AppSettingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AppSetting])
  async appSettings(
    @graphql.Args() args: AppSettingFindManyArgs
  ): Promise<AppSetting[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => AppSetting, { nullable: true })
  async appSetting(
    @graphql.Args() args: AppSettingFindUniqueArgs
  ): Promise<AppSetting | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AppSetting)
  async createAppSetting(
    @graphql.Args() args: CreateAppSettingArgs
  ): Promise<AppSetting> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AppSetting)
  async updateAppSetting(
    @graphql.Args() args: UpdateAppSettingArgs
  ): Promise<AppSetting | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AppSetting)
  async deleteAppSetting(
    @graphql.Args() args: DeleteAppSettingArgs
  ): Promise<AppSetting | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
